[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xe6efff"
yellow = "0xd19a66"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
# blue = "0x61afef"
blue = "0x457ca8"
cyan = "0x56b6c2"
# green = "0x98c379"
green = "0x68c47c"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[cursor]

[colors.primary]
# background = "0x5E5C64"
background = "0x1e2127"
bright_foreground = "0xe6efff"
foreground = "0xabb2bf"

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[scrolling]
history = 5000

[window]
opacity = 0.9
decorations = "full"
startup_mode = "Windowed"
decorations_theme_variant = "Dark"

[window.class]
# general = Alacritty

[window.padding]
x = 3
y = 3

[window.dimensions]
columns = 140
lines = 40
